### ISSUE TITLE
Tour of Duty Hiring Authorities

### ISSUE THREAD

**Issue by krnance** [GSA/innovation.gov#25]
&quot;You can do this too. We are not special snowflakes; these are hiring authorities that are available to every agency in government.&quot;

- Jennifer Anastasoff, Founding Member at U.S. Digital Service

# Summary

## Purpose and Outcomes

**Purpose:** Agencies have the authority to recruit and hire talented individuals on a temporary basis to help bolster strategic initiatives in their organization.

The quality of the people that federal agencies can recruit, hire, and retain has a decisive impact on public-sector performance. Recruiting outside talent is an important avenue for infusing innovative thinking and technologies into the federal workforce. Agencies should try harder to employ a diverse and talented workforce by actively recruiting individuals who can help build a more effective, efficient, and innovative government.

By leveraging temporary tour-of-duty employment opportunities (also known as details), federal agencies can tap into new talent willing to serve their country. Using flexible hiring authorities allows agencies to recruit executives, entrepreneurs, technologists, and other innovators willing to enter government service for a short period.

## Examples

Use flexible hiring models to rapidly recruit top talent with specialized skills. Programs like the General Service Administration&#39;s [Presidential Innovation Fellows](https://presidentialinnovationfellows.gov/) and [18F](https://18f.gsa.gov/), and the [United States Digital Service](https://www.usds.gov) (USDS) in the Executive Office of the President have successfully demonstrated the benefits of recruiting technical and design talent. These recruits significantly improve the delivery of digital services and experiment with new approaches to solve problems.

Agencies can gain similar benefits from using flexible hiring authorities to bring in domain experts in other critical areas besides digital technology, such as process improvement, data science and data-driven decision-making, financial innovation, human-centered design, open source, and agile approaches.

Agencies can quickly address critical skill gaps and further define their most pressing problems and stretch goals. For example, the U.S. Department of Health and Human Services (HHS) has an [Entrepreneur-in-Residence](https://www.hhs.gov/idealab/eir-program/) programs to address some of the tough challenges the department faces.

# Approach

Tour of duty is a temporary employment hiring process available under flexible hiring authorities. This approach allows agencies to meet critical hiring needs at a faster pace than the traditional federal hiring process.

Here are a few flexible hiring authorities that facilitate tour of duty hiring:

- [Direct Hire Authority](https://www.opm.gov/policy-data-oversight/hiring-information/direct-hire-authority/) - with permission from Office of Personnel Management (OPM)
- [Expert and Consultant Pay](http://www.ecfr.gov/cgi-bin/text-idx?rgn=div5;node=5:1.0.1.2.34)
- [Intergovernmental Personnel Act](https://www.opm.gov/policy-data-oversight/hiring-information/intergovernment-personnel-act/) (IPA)
- [Schedule A Part R hiring authority](http://www.ecfr.gov/cgi-bin/text-idx?rgn=div5&amp;node=5:1.0.1.2.22#sg5.1.213.c.sg0)

Understanding and properly using all available flexible hiring authorities can help each agency&#39;s human capital team meet agency hiring needs more efficiently. OPM offers [more guidance](https://www.opm.gov/policy-data-oversight/pay-leave/reference-materials/handbooks/humanresourcesflexibilitiesauthorities.pdf) on different hiring authorities and recruitment approaches.

An effective public service appeal directly asks prospective hires to use their tremendous skills to serve their country. Particularly with fellowship authority ( [Schedule A sub-part R](http://www.ecfr.gov/cgi-bin/text-idx?rgn=div5&amp;node=5:1.0.1.2.22#sg5.1.213.c.sg0)), talent can be hired under two-year appointments with the option of extending another two years. The tour of duty model can appeal to talent with technical expertise who might not have otherwise considered public service.

## Actions and Considerations

Follow these steps to recruit private-sector talent:

### Step 1: Assess the type of program that fits your agency&#39;s hiring needs:

There are five specific reasons why you&#39;d bring in a tour of duty hire--determine which of these your agency needs:

- **Internship or fellowship programs** provide developmental or professional experiences to individuals who have completed their formal education;
- **Training and associate programs** increase the pool of qualified candidates in a particular occupational specialty;
- **Professional/industry exchange programs** provide cross-fertilization between the agency and the private sector to foster mutual understanding and idea exchanges, or to bring experienced practitioners to the agency;
- **Residency programs** help participants gain experience in a federal clinical environment
- **Assistance programs** require a period of government service in exchange for educational, financial, or other assistance.

Consider using [Human Resources University&#39;s Hiring Decision Tool](https://hru.gov/Studio_Recruitment/HT_Hiring_Decision_Tool.aspx) to evaluate what you might need at your agency. The interactive questionnaire can help match potential hiring flexibilities with your agency&#39;s needs.

### Step 2: Pitch your call to serve to private-sector talent

Recruit by using a call to serve. Effective appeals can include:

- Focus on the mission and emphasize outcome-driven goals.
- Highlight the amount of impact an individual can make through the position.
- Point to specific examples of similarly skilled people who have already had widespread impact.

Step 3: Adopt private-sector best practices to actively recruit top talent

### The U.S. Digital Service (USDS) process has six essential stages:

1. Identify the most effective skillsets to address priorities. You&#39;ll need to do considerable internal work to understand and articulate the agency&#39;s talent gaps.
2. Identify who would excel at these skills. Ideal candidates will most likely not be looking for a job. Find them using the tools like LinkedIn, industry blogs, and networks to identify ideal candidates.
3. Use a network to discover and refer a diverse pool of candidates. Use a team approach to connect with experts from around the country and tap into the full range of potential talent.
4. Build relationships with target individuals. Invest time and social media/web resources to identify ideal candidates, initiate contact, present the opportunity, and convey the operating conditions and possible impact.
5. Communicate candidly, directly, and consistently via media and local recruiting events. Events like demo days and roundtables are key for persuading top talent to consider a public service tour of duty.
6. Create a responsive and strong candidate experience during the application and onboarding process. Design internal processes to make it easy to apply and quickly process applications and potential hires. Communicate frequently with the potential applicants to set up interviews and check on the hiring and security clearance process.

### Step 4: Build talent pipelines through demo days and roundtable events

Use demo days and roundtable engagements as two elements in an active recruitment process. For example, the USDS hosts demo days across the country where multiple agencies showcase completed projects to potential candidates. Their talent team host follow-up roundtable discussions of individual case studies with 10 to 12 potential candidates. Candidates are directly asked if they are interested in joining. If they are, they are invited to one-on-one meetings.

### Step 5: Recruit for both technical expertise and cultural fit

Recruit for both technical skills and soft skills that will help private-sector talent adjust to the challenges of the public-sector workplace. Candidates must be able to empathize with public servants who may be risk-averse due to compliance and regulatory concerns. Other soft skills include active listening, respect for different viewpoints, honest communication, patience, and tolerance for bureaucracy.

### Checklist

- Use flexible hiring authorities such as
- Internship or fellowship programs
- Training and associate programs
- Professional/industry exchange programs
- Residency programs
- Assistance programs
- Pitch to private-sector talent with a call to service
- Adopt private-sector best practices for actively recruiting top talent into government
- Recruit for both technical expertise and cultural fit
- Build collaborations between innovators and career federal employees
- Support innovators

# Policies

- [Direct Hire Authority](https://www.opm.gov/policy-data-oversight/hiring-information/direct-hire-authority/) and [Schedule A Part R hiring authority](http://www.ecfr.gov/cgi-bin/text-idx?rgn=div5&amp;node=5:1.0.1.2.22#sg5.1.213.c.sg0)
  - Authorities that allow agencies to do tour of duty hiring.
- [Intergovernmental Personnel Act (IPA)](https://www.opm.gov/policy-data-oversight/hiring-information/intergovernment-personnel-act/)
- [Institutionalizing Hiring Excellence to Achieve Mission Outcomes](https://www.whitehouse.gov/sites/default/files/omb/memoranda/2017/m-17-03.pdf). OMB-M-17-03, November 1, 2016
     - Congress passed many important new hiring flexibilities as part of the [Chief Human Capital Officers Act of 2002](https://www.gpo.gov/fdsys/pkg/PLAW-107https:/www.gpo.gov/fdsys/pkg/PLAW-107publ296/pdf/PLAW-107publ296.pdf). It reinforced the strategic role played by human capital officers in the [Government Performance and Results Modernization Act of 2010](https://www.gpo.gov/fdsys/pkg/BILLS-111hr2142enr/pdf/BILLS-111hr2142enr.pdf).
- [Talent Act of 2017](https://www.congress.gov/bill/115th-congress/house-bill/39) and [Executive Order 13704—Presidential Innovation Fellows Program](https://www.gpo.gov/fdsys/pkg/FR-2015-08-20/pdf/2015-20801.pdf)
  - This order and bill codifies the Presidential Innovation Fellows Program to encourage entrepreneurs, executives, and innovators to join the government and work in close cooperation with government leaders to create meaningful solutions that can help save lives and taxpayer money, fuel job creation, and significantly improve how the government serves the American people.
- [Expert and Consultant Pay](http://www.ecfr.gov/cgi-bin/text-idx?rgn=div5;node=5:1.0.1.2.34)
  - How much money an expert or consultant should be paid

# Additional Resources

- Information on [Hiring Authorities](https://www.opm.gov/policy-data-oversight/hiring-information/hiring-authorities/) for Schedule A or B
- [Delegated Examining Operations Handbook](https://www.opm.gov/policy-data-oversight/hiring-information/competitive-hiring/deo_handbook.pdf)
  - Refer to Chapter 2, Section A for a review of hiring flexibilities
- [Human Resources Flexibilities and Authorities in Federal Government Handbook](https://www.opm.gov/policy-data-oversight/pay-leave/reference-materials/handbooks/humanresourcesflexibilitiesauthorities.pdf)
- [OPM&#39;s Hiring Excellence Campaign](https://www.opm.gov/policy-data-oversight/hiring-information/hiring-excellence/tools-resources/) (HEC) and [Hiring Excellence Mythbusters](https://www.opm.gov/policy-data-oversight/hiring-information/hiring-excellence/tools-resources/hiring-excellence-mythbusters.pdf)
- Human Resources University&#39;s [Excepted Service Hiring](https://hru.gov/Studio_Recruitment/HT_04_Schedules.aspx#pnlToolkit), which includes how-to steps for:
  - [Hiring Toolkit and Decision Tool](https://hru.gov/Studio_Recruitment/HT_Hiring_Toolkit.aspx)
  - [Intergovernmental Personnel Act (IPA)](https://hru.gov/Studio_Recruitment/HT_05_Intergovernmental_Personnel_Act.aspx#pnlToolkit)
    - Making 30-Day Critical Hiring Need Appointment
  - [Recruitment Policy Studio](https://hru.gov/Studio_Recruitment/Studio_Recruitment.aspx)
    - Resources specific to flexible hiring authorities:
  - [Schedule D – Pathways Programs](https://hru.gov/Studio_Recruitment/HT_05_Schedule_D_-_Pathways_Programs.aspx#pnlToolkit)
    - Using OPM-approved Schedule A hiring authority for Digital Services

**Comment by krnance** [comment]
i recall conversation about the bulleting style but don't know the resolution.

**Comment by brookarch** [comment]
Kelly - this is awesome! I will do the clean up for the headings and bullets.
