### ISSUE TITLE
Broken link under Human-Centered Design Resources

### ISSUE THREAD

**Issue by joeforyou** [GSA/innovation.gov#81]
[This link](https://www.gsa.gov/blog/files/2017/10/HCD-Discovery-Guide-Interagency-v1.2-1.pdf) to the Lab at OPM's Human-Centered Design Discovery Stage Field Guide is currently broken.

The link appears in the Resources section [on this page](https://innovation.gov/toolkit/delivery/#human-centered).

**Comment by atrain440** [comment]
@joeforyou: Thanks for pointing out. That link was removed and I've since added a link for a PDF download of the document.
